### ISSUE TITLE
Create all the modules

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/SlicerOpenLIFU#56]
Here are the modules we will have:
- OpenLIFU Home (already exists)
- OpenLIFU Data
- OpenLIFU Pre-Planning
- OpenLIFU Transducer Tracking
- OpenLIFU Sonication Planning
- OpenLIFU Sonication Control
- OpenLIFU Protocol Configuration

Here are the things to do:
- Create all the modules, as blank modules for now. We can just put a QLabel that says "module under construction" or something (some of them may remain under construction for a while)
- Move all the database and session loading stuff that is introduced in #50 into the OpenLIFU Data Module and out of OpenLIFUHome
- Put buttons in OpenLIFUHome that take you to all the other modules. We can group Data, pre-planning, transducer tracking, sonication planning, and sonication control into one set. Then Protocol configuration can be off by itself as a separate thing.

**Comment by sadhana-r** [comment]
When building the Slicer extension on Windows, there is a 260 character OS "max path limit". Therefore, few of the the module folder names had to be adjusted:

- OpenLIFUTransducerTracking --> OpenLIFUTransducerTracker
- OpenLIFUSonicationPlanning -->  OpenLIFUSonicationPlanner
- OpenLIFUProtocolConfiguration --> OpenLIFUProtocolConfig

Note: The module names that show up in Slicer have not be adjusted.

**Comment by ebrahimebrahim** [comment]
Ah I always forget about that max path limit thing... the rename seems good to me

> Note: The module names that show up in Slicer have not be adjusted.

What did you mean by this?

**Comment by sadhana-r** [comment]
> > Note: The module names that show up in Slicer have not be adjusted.
> 
> What did you mean by this?

For example, within the Slicer UI, the module is still called "OpenLIFU Transducer Tracking" since that sounds nicer but the source code folders/files are called OpenLIFUTransducerTracker" to reduce the character count.

**Comment by ebrahimebrahim** [comment]
Closed by #67
